# Deploy contexts
# Environment variables here override variables set in the web UI.
#
# https://docs.netlify.com/site-deploys/overview/#deploy-contexts
# https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts

[context.deploy-preview.environment]
  HUGO_VERSION = "0.81.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.81.0"

[context.production.environment]
  HUGO_VERSION = "0.81.0"

# Redirects
# - Default status is a 301 unless otherwise specified.
# - First match wins: put wildcards AFTER specific paths!
# - Wildcards include empty matches: /v1.0/* WILL match /v1.0 
#
# docs: https://docs.netlify.com/routing/redirects/
#
# validator: https://play.netlify.com/redirects

# Make sure we're not redirecting anything under /images

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

# Legal, FAQ, and release notes should always point to the latest,
# even if we have content in the older version's folder.

[[redirects]]
  from = "/:version/comparisons/*"
  to = "/latest/comparisons/:splat"
  force = true

[[redirects]]
  from = "/:version/contribute/*"
  to = "/latest/contribute/:splat"
  force = true

[[redirects]]
  from = "/:version/faq/*"
  to = "/latest/faq/:splat"
  force = true

[[redirects]]
  from = "/:version/legal/*"
  to = "/latest/legal/:splat"
  force = true

[[redirects]]
  from = "/:version/releases/*"
  to = "/latest/releases/:splat"
  force = true

# Stable quick-starts need defaults,
# since archiving from /latest removes aliases

[[redirects]]
  from = "/stable/quick-start/install/"
  to = "/stable/quick-start/install/macos/"
  force = true

[[redirects]]
  from = "/stable/quick-start/create-local-cluster/"
  to = "/stable/quick-start/create-local-cluster/macos/"
  force = true

[[redirects]]
  from = "/stable/quick-start/explore/"
  to = "/stable/quick-start/explore/ysql/"
  force = true

# Misc old docs with paths that have changed

[[redirects]]
  from = "/v1.1/explore/cloud-native/binary/observability/"
  to = "/latest/explore/observability/"
  force = true

[[redirects]]
  from="/stable/quick-start/install/"
  to="/stable/quick-start/install/macos/"

# Docs prior to v1.3 are not online

[[redirects]]
  from = "/v1.0/*"
  to = "/latest/:splat"
  force = true

[[redirects]]
  from = "/v1.1/*"
  to = "/latest/:splat"
  force = true

[[redirects]]
  from = "/v1.2/*"
  to = "/latest/:splat"
  force = true

# Hugo resource caching plugin configuration
# https://github.com/cdeleeuwe/netlify-plugin-hugo-cache-resources#readme

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

    [plugins.inputs]
    # If it should show more verbose logs (optional, default = true)
    debug = true
    # Relative path to source directory in case you use Hugo's "--s" option
    srcdir = "docs"
